title: Other People's Flowers
email: editor@otherpeoplesflowers.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://otherpeoplesflowers.com"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass
