* Published Email
Hi David,

Just to let you know we published Country Man today. Here are a few links:

https://itunes.apple.com/gb/podcast/other-peoples-flowers/id1351210915?mt=2
https://player.fm/series/series-2182071
https://www.stitcher.com/podcast/other-peoples-flowers
https://anchor.fm/other-peoples-flowers
https://www.podbean.com/podcast-detail/tw73f-672dc/Other-People's-Flowers-Podcast

Thanks so much for sending us your story. We really enjoyed it and hopefully you'll think of us again in the future. 

Best Wishes,

Hugo and Kriskamol

P.S. If you want help promote your work, the best thing you can do is give us a positive (or negative!) review on whichever podcast platform you listen on.
* Accepted Email
Hi Michael,

We'd love to feature The Squall on the show. There's nothing you need to do at this stage. We will record it and released it in the next couple of weeks and let you know once we've released. If you want to withdraw it for any reason, then please let us know and we won't record it.

Sometimes stories have been accepted elsewhere in print. Usually we can record it as well, but it's up to the print magazine so if this is the case and you still want us to record it, let us know.

Many thanks,
Hugo
* Content
[Fiction, Storytelling] **Other People's Flowers | Episode 20**

**NSFW (occasional language)**

[Website](http://www.otherpeoplesflowers.com/) // [iTunes](https://itunes.apple.com/gb/podcast/other-peoples-flowers/id1351210915?mt=2) // [Android] (http://subscribeonandroid.com/feeds.soundcloud.com/users/soundcloud:users:403045977/sounds.rss) // [Stitcher](https://www.stitcher.com/podcast/other-peoples-flowers?refid=stpr) // [YouTube](https://www.youtube.com/channel/UCqdO8A-jfzr8CZGdCEzxl7A) // [Blubrry](https://www.blubrry.com/otherpeoplesflowers/) // [Podbean](https://www.podbean.com/podcast-detail/tw73f-672dc/Other-People%27s-Flowers-Podcast) // [Soundcloud] (https://soundcloud.com/other-peoples-flowers)

This week we're featuring a short story by Steve Carr, called a A
Woman of the Arts.

Steve Carr, who lives in Richmond, Va., began his writing career as a military journalist and has had over 170 short stories published internationally in print and online magazines, literary journals and anthologies. Sand, a collection of his short stories, was published recently by Clarendon House Books. His plays have been produced in several states in the U.S. He was a 2017 Pushcart Prize nominee.

Other People's Flowers is the podcast that showcases short stories, essays, and reportage. We're the first podcast-based literary journal. People hardly read journals anymore so we hope you'll listen instead.

If you'd like to have your work featured on the show, please send it to editor@otherpeoplesflowers.com

http://www.otherpeoplesflowers.com

* Timings
** Steve Carr
3.27 - Before Robert admitted she too had never married
Bit more of a gap between the end and the credits
* Classified for PW.org

OTHER PEOPLE'S FLOWERS is a literary podcast showcasing fiction, essays, and poetry. We aim to give voice to emerging and established writers by featuring them on our podcast. Send your work to editor@otherpeoplesflowers.com. Submissions are open throughout the year. There is no reading fee, but please be aware response times can vary during busier periods. Visit: www.otherpeoplesflowers.com or find us on iTunes or your favourite podcasting platform.
