* Published Email
Hi Jeffery,

Just to let you know we published your episode today. Here are a few links:


Thanks so much for sending us your poetry. We really enjoyed it and hopefully you'll think of us again in the future. 

Best Wishes,

Hugo and Kriskamol

P.S. If you want help promote your work, the best thing you can do is give us a positive (or negative!) review on whichever podcast platform you listen on.
* Content
[Fiction, Storytelling] **Other People's Flowers | Episode 20**

**NSFW (occasional language)**

[Website](http://www.otherpeoplesflowers.com/) // [iTunes](https://itunes.apple.com/gb/podcast/other-peoples-flowers/id1351210915?mt=2) // [Android] (http://subscribeonandroid.com/feeds.soundcloud.com/users/soundcloud:users:403045977/sounds.rss) // [Stitcher](https://www.stitcher.com/podcast/other-peoples-flowers?refid=stpr) // [YouTube](https://www.youtube.com/channel/UCqdO8A-jfzr8CZGdCEzxl7A) // [Blubrry](https://www.blubrry.com/otherpeoplesflowers/) // [Podbean](https://www.podbean.com/podcast-detail/tw73f-672dc/Other-People%27s-Flowers-Podcast) // [Soundcloud] (https://soundcloud.com/other-peoples-flowers)

This week we're featuring a short story by Pete Stavros, called Twenty
Good Years. Twenty Good Years is due to be published in Thoughtful Dog (https://www.thoughtfuldogmag.com/).

Peter J. Stavros is a writer in Louisville, Kentucky. His work has
appeared in The Saturday Evening Post, The Boston Globe Magazine, The
East Bay Review, Hypertext Magazine, Fiction Southeast, Juked, and
Literary Orphans, among others. Peter has also had plays produced,
including as part of the Festival of Ten at The College at Brockport –
SUNY, for which he was named Audience Choice Winner. More can be found
at www.peterjstavros.com.

Other People's Flowers is the podcast that showcases short stories, essays, and reportage. We're the first podcast-based literary journal. People hardly read journals anymore so we hope you'll listen instead.

If you'd like to have your work featured on the show, please send it to editor@otherpeoplesflowers.com

http://www.otherpeoplesflowers.com

* Timings
** Patricia
** Robert and Veronica
  - Too many Pauses at beginning, right up until it actually starts.
** Ted DeMarsh
 - 5:11, repeated This, they would be
** JJ Steinfeld
Thanks so much for sending us your work. We're very sorry to hear about your friend. Mental health is subject very close to both of our hearts. We will read your story and get back to you as soon as we can.
** Jeffery Berg
Beggining - Virginia Centre bit
Many thanks,
 Hugo and Kriskamol


I'm heading off but https://github.com/simba-sleep/node-divido-api has
two outstanding PRs, one for a swagger spec (which has been sent to
Divido) and one for the api implementing this spec. The api is
basically done, but the auth is not done at all, and it could do with
better logging. It will also need to be deployed in some way.
* Classified for PW.org

OTHER PEOPLE'S FLOWERS is a literary podcast showcasing fiction, essays, and poetry. We aim to give voice to emerging and established writers by featuring them on our podcast. Send your work to editor@otherpeoplesflowers.com. Submissions are open throughout the year. There is no reading fee, but please be aware response times can vary during busier periods. Visit: www.otherpeoplesflowers.com or find us on iTunes or your favourite podcasting platform.
